name: build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: cmake build
        run: mkdir build && cd build && cmake .. && make

      - name: run
        run: cd build && ./PacketProcessor_test
